<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Core\Module' => __DIR__ . '/Module.php',
    'Core\ServiceManager\AbstractControllerFactory' => __DIR__ . '/Core/ServiceManager/AbstractControllerFactory.php'
);
