<?= $this->doctype() ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('JS Peças')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css')
            ->appendStylesheet($this->basePath('../../js/ext-6.2.0/theme-neptune/resources/theme-neptune-all.css'))
            // ->appendStylesheet($this->basePath('/js/ext-6.2.0/theme-classic/resources/theme-classic-all.css'))
            ->appendStylesheet($this->basePath('../../js/noty-3.1.4/noty.min.css'))
            ->appendStylesheet($this->basePath('css/style.css?_dc='.md5(date('H:m:s:u'))))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile($this->basePath('../../js/jquery-3.4.1.min.js'))
            ->appendFile($this->basePath('../../js/ext-6.2.0/ext-all.js'))
            ->appendFile($this->basePath('../../js/ext-6.2.0/locale-pt_BR.js'))
            ->appendFile($this->basePath('../../js/noty-3.1.4/noty.min.js'))
            ->appendScript("var BASEURL = '".$this->basePath()."'", $type = 'text/javascript')
        ?>
    </head>
    <body>
        <?= $this->inlineScript() ?>
        <?= $this->content ?>
    </body>
</html>
